// Code generated by ogen, DO NOT EDIT.
package oas

type V1AuthLoginRes interface {
	v1AuthLoginRes()
}

type V1AuthRefreshRes interface {
	v1AuthRefreshRes()
}

type V1OTPCodeEnterRes interface {
	v1OTPCodeEnterRes()
}

type V1OTPCodeSendRes interface {
	v1OTPCodeSendRes()
}

type V1UsersCreateRes interface {
	v1UsersCreateRes()
}

type V1UsersMeRes interface {
	v1UsersMeRes()
}

type V1UsersMeUpdateRes interface {
	v1UsersMeUpdateRes()
}
