// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"github.com/go-faster/errors"
)

func (s V1GetUserListOKApplicationJSON) Validate() error {
	alias := ([]V1User)(s)
	if alias == nil {
		return errors.New("nil is invalid value")
	}
	return nil
}
