// Code generated by ogen, DO NOT EDIT.
package oas

type V1UsersCreateRes interface {
	v1UsersCreateRes()
}

type V1UsersMeRes interface {
	v1UsersMeRes()
}

type V1UsersMeUpdateRes interface {
	v1UsersMeUpdateRes()
}
