// Code generated by ogen, DO NOT EDIT.

package oas

import (
	"context"
)

// Handler handles operations described by OpenAPI v3 specification.
type Handler interface {
	// V1UsersCreate implements V1_Users_Create operation.
	//
	// Creates and returns a new user.
	//
	// POST /v1/users
	V1UsersCreate(ctx context.Context, req *V1UsersCreateReq) (V1UsersCreateRes, error)
	// V1UsersMe implements V1_Users_Me operation.
	//
	// Gets the current user.
	//
	// GET /v1/users/me
	V1UsersMe(ctx context.Context) (V1UsersMeRes, error)
	// V1UsersMeUpdate implements V1_Users_Me_Update operation.
	//
	// Updates the current user.
	//
	// PATCH /v1/users/me
	V1UsersMeUpdate(ctx context.Context, req OptV1UsersMeUpdateReq) (V1UsersMeUpdateRes, error)
}

// Server implements http server based on OpenAPI v3 specification and
// calls Handler to handle requests.
type Server struct {
	h   Handler
	sec SecurityHandler
	baseServer
}

// NewServer creates new Server.
func NewServer(h Handler, sec SecurityHandler, opts ...ServerOption) (*Server, error) {
	s, err := newServerConfig(opts...).baseServer()
	if err != nil {
		return nil, err
	}
	return &Server{
		h:          h,
		sec:        sec,
		baseServer: s,
	}, nil
}
