// Code generated by ogen, DO NOT EDIT.

package oas

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// V1GetUserByIDDef is default response for V1GetUserByID operation.
type V1GetUserByIDDef struct {
	StatusCode int
}

// GetStatusCode returns the value of StatusCode.
func (s *V1GetUserByIDDef) GetStatusCode() int {
	return s.StatusCode
}

// SetStatusCode sets the value of StatusCode.
func (s *V1GetUserByIDDef) SetStatusCode(val int) {
	s.StatusCode = val
}

func (*V1GetUserByIDDef) v1GetUserByIDRes() {}

// Ref: #
type V1User struct {
	ID        OptInt64  `json:"id"`
	Name      OptString `json:"name"`
	PhotoUrls []string  `json:"photoUrls"`
}

// GetID returns the value of ID.
func (s *V1User) GetID() OptInt64 {
	return s.ID
}

// GetName returns the value of Name.
func (s *V1User) GetName() OptString {
	return s.Name
}

// GetPhotoUrls returns the value of PhotoUrls.
func (s *V1User) GetPhotoUrls() []string {
	return s.PhotoUrls
}

// SetID sets the value of ID.
func (s *V1User) SetID(val OptInt64) {
	s.ID = val
}

// SetName sets the value of Name.
func (s *V1User) SetName(val OptString) {
	s.Name = val
}

// SetPhotoUrls sets the value of PhotoUrls.
func (s *V1User) SetPhotoUrls(val []string) {
	s.PhotoUrls = val
}

func (*V1User) v1GetUserByIDRes() {}
