version: "3.9"
services:
  postgres:
    image: postgres:16-alpine
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    volumes:
      - db:/var/lib/postgresql/data

  cache:
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    volumes: 
      - cache:/data

  mailhog:
    image: mailhog/mailhog
    restart: always
    ports:
      - "8025:8025"

volumes:
  db:
    driver: local
  cache:
    driver: local