output   = "internal/models"
wipe     = true
no-tests = true
add-enum-types = true

[psql]
    dbname = "go_api"
    host   = "localhost"
    port   = 5432
    user   = "postgres"
    pass   = "postgres"
    sslmode = "disable"
    blacklist = ["migrations"]