// Code generated by SQLBoiler 4.15.0 (https://github.com/volatiletech/sqlboiler). DO NOT EDIT.
// This file is meant to be re-generated in place and/or deleted at any time.

package models

var TableNames = struct {
	AccessTokens     string
	Otp              string
	RefreshTokens    string
	SchemaMigrations string
	Users            string
}{
	AccessTokens:     "access_tokens",
	Otp:              "otp",
	RefreshTokens:    "refresh_tokens",
	SchemaMigrations: "schema_migrations",
	Users:            "users",
}
