openapi: 3.0.2

servers:
  - url: /v3

info:
  version: 1.0.0
  title: Go API

tags:
  - name: users
    description: Everything related to users

paths:
  /v1/users:
    $ref: "./v1/paths/users.yml"

  /v1/users/{id}:
    $ref: "./v1/paths/users_id.yml"

