openapi: 3.0.2

servers:
  - url: /v3

info:
  version: 1.0.0
  title: Go API

tags:
  - name: user
    description: Everything related to users

paths:
  /v1/user/{id}:
    $ref: "./v1/paths/users_by_id.yml"
